BRICK = {
    "brick_num": 4,
    "brick_title": "Metabolic Overview II: OXPHOS Uncouplers and Inhibitors",
    "games": [
        {
            "slug": "oxphos_inhibitors",
            "title": "OXPHOS Toxins: Site and Source",
            "subtitle": "Match each ETC/OXPHOS inhibitor to its typical source, molecular target, and a distinguishing feature",
            "categories": ["Source / Exposure", "Target in OXPHOS", "Distinguishing Feature"],
            "data": {
                "Rotenone": {
                    "Source / Exposure": "Roots of plants from Asia, South America, East Africa; pesticide and fish control",
                    "Target in OXPHOS": "Complex I",
                    "Distinguishing Feature": "Poorly absorbed through skin, so accidental human poisoning is rare"
                },
                "Antimycin A": {
                    "Source / Exposure": "Bacterial product used in fungicides and fishery management",
                    "Target in OXPHOS": "Complex III",
                    "Distinguishing Feature": "Exposure usually occupational or via treated recreational water"
                },
                "Cyanide (CN)": {
                    "Source / Exposure": "HCN gas from structural fires, nitroprusside, cassava and select nuts",
                    "Target in OXPHOS": "Complex IV",
                    "Distinguishing Feature": "Cherry-red skin and serum lactate profoundly elevated above 8 mmol/L"
                },
                "Carbon monoxide (CO)": {
                    "Source / Exposure": "Incomplete combustion: generators, heaters, wood stoves, structural fires",
                    "Target in OXPHOS": "Complex IV",
                    "Distinguishing Feature": "Altered hemoglobin-oxygen binding is the primary clinical concern"
                },
                "Oligomycin": {
                    "Source / Exposure": "Bacterial product used mainly in metabolic research labs",
                    "Target in OXPHOS": "ATP synthase (Complex V)",
                    "Distinguishing Feature": "Blocks proton flow through the synthase rather than electron flow"
                },
                "Formic acid": {
                    "Source / Exposure": "Bee sting or oxidative catabolism of ingested methanol (antifreeze)",
                    "Target in OXPHOS": "Complex IV",
                    "Distinguishing Feature": "Requires metabolic activation, unlike the direct-acting inhibitors"
                }
            }
        },
        {
            "slug": "uncoupler_vs_inhibitor",
            "title": "Uncouplers vs. ETC Inhibitors",
            "subtitle": "Sort each metabolic consequence to what an uncoupler does versus what an ETC inhibitor does",
            "categories": ["Uncoupler (e.g., DNP)", "ETC Inhibitor (e.g., cyanide)"],
            "data": {
                "Effect on electron flow through the ETC": {
                    "Uncoupler (e.g., DNP)": "Continues, and even accelerates initially",
                    "ETC Inhibitor (e.g., cyanide)": "Blocked from the start of exposure"
                },
                "Effect on oxygen consumption": {
                    "Uncoupler (e.g., DNP)": "Increases initially as electron transport speeds up",
                    "ETC Inhibitor (e.g., cyanide)": "Decreases from the start as O2 can no longer be consumed"
                },
                "Reactive oxygen species (ROS)": {
                    "Uncoupler (e.g., DNP)": "Not a hallmark; can even reduce oxidative stress",
                    "ETC Inhibitor (e.g., cyanide)": "Generated by inefficient, blocked electron transfer"
                },
                "Heat / thermogenesis": {
                    "Uncoupler (e.g., DNP)": "Hallmark non-shivering thermogenesis; energy becomes heat",
                    "ETC Inhibitor (e.g., cyanide)": "Not a defining feature of inhibition"
                },
                "Reduced coenzymes (NADH, FADH2)": {
                    "Uncoupler (e.g., DNP)": "Oxidized faster as oxidative catabolism increases",
                    "ETC Inhibitor (e.g., cyanide)": "Accumulate because the blocked ETC cannot oxidize them"
                },
                "Proton gradient across inner membrane": {
                    "Uncoupler (e.g., DNP)": "Dissipated through an alternate route apart from ATP synthase",
                    "ETC Inhibitor (e.g., cyanide)": "Collapses because pumping ceases when electrons stop flowing"
                }
            }
        },
        {
            "slug": "cn_poisoning_vs_cyanosis",
            "title": "Cyanide Poisoning vs. Cyanosis",
            "subtitle": "These look-alike terms are frequent distractors; match each feature to the correct entity",
            "categories": ["Cyanide Poisoning", "Cyanosis"],
            "data": {
                "Skin color": {
                    "Cyanide Poisoning": "Cherry-red skin discoloration",
                    "Cyanosis": "Blue-tinted skin, most visible in lips, fingers, toes, nailbeds"
                },
                "Underlying mechanism": {
                    "Cyanide Poisoning": "Complex IV inhibition prevents tissue oxygen consumption",
                    "Cyanosis": "Inadequate delivery of oxygenated hemoglobin to tissues"
                },
                "State of hemoglobin at the tissue": {
                    "Cyanide Poisoning": "Remains oxygenated because O2 is not extracted",
                    "Cyanosis": "Deoxygenated hemoglobin predominates"
                },
                "Representative cause": {
                    "Cyanide Poisoning": "Fire smoke, nitroprusside, or cyanogenic foods like cassava",
                    "Cyanosis": "Congenital heart defect or reduced hemoglobin synthesis"
                },
                "Preferred management": {
                    "Cyanide Poisoning": "Hydroxocobalamin (a form of vitamin B12)",
                    "Cyanosis": "Correct the underlying perfusion or hemoglobin problem"
                }
            }
        },
        {
            "slug": "natural_vs_unnatural_uncouplers",
            "title": "Natural vs. Unnatural Uncouplers",
            "subtitle": "Contrast physiologic uncoupling proteins with chemical uncoupling agents",
            "categories": ["Natural (UCPs)", "Unnatural (e.g., DNP)"],
            "data": {
                "Chemical nature": {
                    "Natural (UCPs)": "Proteins (uncoupling proteins such as UCP-1)",
                    "Unnatural (e.g., DNP)": "Lipid-soluble chemical agents"
                },
                "Relationship to the inner membrane": {
                    "Natural (UCPs)": "Span the membrane and act as regulated proton transporters",
                    "Unnatural (e.g., DNP)": "Freely diffuse across the membrane, not anchored in it"
                },
                "What controls their abundance": {
                    "Natural (UCPs)": "Tissue-specific gene expression that can be turned on and off",
                    "Unnatural (e.g., DNP)": "Determined by intake or exposure, not genetic control"
                },
                "Tissue distribution": {
                    "Natural (UCPs)": "Restricted to specialized tissue such as brown adipose tissue",
                    "Unnatural (e.g., DNP)": "Broad and indiscriminate, including brain and liver"
                },
                "Physiologic role or danger": {
                    "Natural (UCPs)": "Beneficial thermogenesis, e.g., newborn warmth and hibernation",
                    "Unnatural (e.g., DNP)": "Toxic gradient collapse with no safe dose and no antidote"
                }
            }
        }
    ]
}
