BRICK = {
    "brick_num": 7,
    "brick_title": "Nitrogenous Base Metabolism",
    "games": [
        {
            "slug": "bases_and_nucleic_acids",
            "title": "The Five Nitrogenous Bases",
            "subtitle": "Match each base to its class, where it is found, and a distinguishing metabolic note",
            "categories": ["Base Class", "Nucleic Acid Location", "Distinguishing Note"],
            "data": {
                "Adenine": {
                    "Base Class": "Purine (double ring)",
                    "Nucleic Acid Location": "Both DNA and RNA",
                    "Distinguishing Note": "Deaminated by adenosine deaminase (ADA) to IMP before degradation; salvaged by APRT"
                },
                "Guanine": {
                    "Base Class": "Purine (double ring)",
                    "Nucleic Acid Location": "Both DNA and RNA",
                    "Distinguishing Note": "Directly produces uric acid via xanthine oxidase"
                },
                "Cytosine": {
                    "Base Class": "Pyrimidine (single ring)",
                    "Nucleic Acid Location": "Both DNA and RNA",
                    "Distinguishing Note": "Derived from UMP; synthesis is folate-independent"
                },
                "Thymine": {
                    "Base Class": "Pyrimidine (single ring)",
                    "Nucleic Acid Location": "DNA only",
                    "Distinguishing Note": "dTMP is made from dUMP by thymidylate synthase using a folate one-carbon donation"
                },
                "Uracil": {
                    "Base Class": "Pyrimidine (single ring)",
                    "Nucleic Acid Location": "RNA only",
                    "Distinguishing Note": "Salvaged onto PRPP by pyrimidine phosphoribosyl transferase to reform UMP"
                }
            }
        },
        {
            "slug": "synthesis_enzymes",
            "title": "Enzymes of Nucleotide Synthesis",
            "subtitle": "Match each enzyme to its pathway, the reaction it catalyzes, and its regulation",
            "categories": ["Pathway", "Reaction Catalyzed", "Regulation / Note"],
            "data": {
                "PRPP synthetase": {
                    "Pathway": "Feeds both purine and pyrimidine de novo synthesis and salvage",
                    "Reaction Catalyzed": "Adds pyrophosphate from ATP to ribose 5-phosphate to form PRPP",
                    "Regulation / Note": "Inhibited by purine nucleotide end products; not the committed step"
                },
                "Glutamine PRPP amidotransferase": {
                    "Pathway": "De novo purine synthesis",
                    "Reaction Catalyzed": "Donates a glutamine nitrogen onto carbon 1 of PRPP",
                    "Regulation / Note": "Committed step; activated by PRPP, inhibited by AMP, GMP, and IMP"
                },
                "Carbamoyl phosphate synthetase II (CPSII)": {
                    "Pathway": "De novo pyrimidine synthesis",
                    "Reaction Catalyzed": "Makes carbamoyl phosphate from glutamine, CO2, and ATP in the cytoplasm",
                    "Regulation / Note": "Enhanced by PRPP, suppressed by UTP"
                },
                "Uridine monophosphate synthase (UMPS)": {
                    "Pathway": "De novo pyrimidine synthesis",
                    "Reaction Catalyzed": "Converts orotic acid into UMP using PRPP",
                    "Regulation / Note": "Deficiency causes hereditary orotic aciduria"
                },
                "Ribonucleotide reductase": {
                    "Pathway": "Deoxyribonucleotide (DNA substrate) production",
                    "Reaction Catalyzed": "Reduces the 2' carbon of the ribose sugar to deoxyribose",
                    "Regulation / Note": "Uses reduced thioredoxin regenerated by NADPH; all nucleotides pass through it except dTMP"
                },
                "Thymidylate synthase": {
                    "Pathway": "dTMP (thymidine) synthesis",
                    "Reaction Catalyzed": "Transfers a methyl group from methylene-FH4 onto dUMP",
                    "Regulation / Note": "Generates DHF; inhibited when 5-fluorouracil is salvaged to FdUMP"
                }
            }
        },
        {
            "slug": "disorders",
            "title": "Disorders of Nitrogenous Base Metabolism",
            "subtitle": "Match each disorder to its enzyme/pathway defect, key feature, and characteristic association",
            "categories": ["Enzyme / Pathway Defect", "Key Clinical Feature", "Characteristic Association"],
            "data": {
                "Gout": {
                    "Enzyme / Pathway Defect": "Purine catabolism; overproduction or underexcretion of uric acid",
                    "Key Clinical Feature": "Rapid-onset painful arthritis, most often the hallux MTP joint, with needle-shaped negatively birefringent crystals",
                    "Characteristic Association": "Managed with allopurinol, colchicine, probenecid, and NSAIDs"
                },
                "ADA-SCID": {
                    "Enzyme / Pathway Defect": "Adenosine deaminase deficiency in purine catabolism",
                    "Key Clinical Feature": "Loss of B and T cells with prone to opportunistic infections",
                    "Characteristic Association": "Accounts for roughly 10-20% of all SCID cases"
                },
                "Lesch-Nyhan syndrome": {
                    "Enzyme / Pathway Defect": "HGPRT deficiency in purine salvage",
                    "Key Clinical Feature": "Crippling gout, self-mutilation, aggressive behavior, and neurologic/muscle tone impairment",
                    "Characteristic Association": "Intact immune system; life expectancy often under 30 years"
                },
                "Hereditary orotic aciduria": {
                    "Enzyme / Pathway Defect": "UMPS deficiency in pyrimidine synthesis",
                    "Key Clinical Feature": "Macrocytic anemia with orotic aciduria and no hyperammonemia",
                    "Characteristic Association": "Treated with uridine or UMP supplementation to bypass the block"
                },
                "OTC deficiency": {
                    "Enzyme / Pathway Defect": "Ornithine transcarbamoylase deficiency in the urea cycle",
                    "Key Clinical Feature": "Orotic aciduria with hyperammonemia and no anemia",
                    "Characteristic Association": "Accumulated carbamoyl phosphate spills into the pyrimidine pathway"
                }
            }
        },
        {
            "slug": "drugs",
            "title": "Drugs Targeting Nucleotide Metabolism",
            "subtitle": "Match each drug to its target/mechanism, its downstream effect, and its clinical use",
            "categories": ["Target / Mechanism", "Downstream Effect", "Clinical Use"],
            "data": {
                "Allopurinol": {
                    "Target / Mechanism": "Free purine analogue that covalently inhibits xanthine oxidase",
                    "Downstream Effect": "Decreases uric acid production",
                    "Clinical Use": "Long-term gout management"
                },
                "Colchicine": {
                    "Target / Mechanism": "Inhibits microtubule polymerization",
                    "Downstream Effect": "Prevents phagocytosis of urate crystals, blunting inflammation",
                    "Clinical Use": "Acute gout flare"
                },
                "Methotrexate": {
                    "Target / Mechanism": "Inhibits dihydrofolate reductase (DHFR)",
                    "Downstream Effect": "Depletes the FH4 pool, limiting dTMP and purine synthesis",
                    "Clinical Use": "Chemotherapy / rapidly dividing cells"
                },
                "6-Mercaptopurine": {
                    "Target / Mechanism": "Salvaged by HGPRT to TIMP, which inhibits glutamine PRPP amidotransferase",
                    "Downstream Effect": "Blocks de novo purine production, depriving cancer cells of DNA substrates",
                    "Clinical Use": "Anticancer prodrug"
                },
                "5-Fluorouracil": {
                    "Target / Mechanism": "Converted to FdUMP, which inhibits thymidylate synthase",
                    "Downstream Effect": "Prevents dTMP production and DNA synthesis",
                    "Clinical Use": "Anticancer prodrug"
                }
            }
        }
    ]
}
